micronaut:
  application:
    name: micronautDemo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
dataSource:
  url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  pooled: true
  jmxExport: true
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: update
  show_sql: true
  cache:
      queries: false
      use_second_level_cache: false
      use_query_cache: false
r2dbc:
  datasources:
    default:
      url: r2dbc:h2:mem:///devDb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''

api:
  key: 9ecd4d849bec4bad904195112210302
  url: https://api.weatherapi.com/v1/current.json
  example: https://api.weatherapi.com/v1/current.json?key=9ecd4d849bec4bad904195112210302&q=plano,tx

endpoints:
  loggers:
    enabled: true
logger:
  levels:
    sci:
      category:
        geovisit: DEBUG
